def auth_header():
    return {
        "x-api-key": "live_MhXwjew5ges6i6eWXn9CDk56UX08g37L8A3nkPnrlLcDPouOitL2bChxOHDoBvOF"
    }


def extract_cat_details(i):
    return {
        "id": i["id"],
        "name": i["name"],
        "temperament": i["temperament"],
        "origin": i["origin"],
        "description": i["description"],
        "life_span": i["life_span"],
        "adaptability": i["adaptability"],
        "affection_level": i["affection_level"],
        "child_friendly": i["child_friendly"],
        "grooming": i["grooming"],
        "health_issues": i["health_issues"],
        "intelligence": i["intelligence"],
        "social_needs": i["social_needs"],
        "stranger_friendly": i["stranger_friendly"],
        "wikipedia_url": i["wikipedia_url"],
        "image": i["image"],
    }


def extract_breed_details(i):
    return {
        "id": i["id"],
        "name": i["name"],
    }


def mock_breed_list_data():
    return [
        {
            "weight": {"imperial": "7  -  10", "metric": "3 - 5"},
            "id": "abys",
            "name": "Abyssinian",
            "cfa_url": "http://cfa.org/Breeds/BreedsAB/Abyssinian.aspx",
            "vetstreet_url": "http://www.vetstreet.com/cats/abyssinian",
            "vcahospitals_url": "https://vcahospitals.com/know-your-pet/cat-breeds/abyssinian",
            "temperament": "Active, Energetic, Independent, Intelligent, Gentle",
            "origin": "Egypt",
            "country_codes": "EG",
            "country_code": "EG",
            "description": "The Abyssinian is easy to care for, and a joy to have in your home. They’re affectionate cats and love both people and other animals.",
            "life_span": "14 - 15",
            "indoor": 0,
            "lap": 1,
            "alt_names": "",
            "adaptability": 5,
            "affection_level": 5,
            "child_friendly": 3,
            "dog_friendly": 4,
            "energy_level": 5,
            "grooming": 1,
            "health_issues": 2,
            "intelligence": 5,
            "shedding_level": 2,
            "social_needs": 5,
            "stranger_friendly": 5,
            "vocalisation": 1,
            "experimental": 0,
            "hairless": 0,
            "natural": 1,
            "rare": 0,
            "rex": 0,
            "suppressed_tail": 0,
            "short_legs": 0,
            "wikipedia_url": "https://en.wikipedia.org/wiki/Abyssinian_(cat)",
            "hypoallergenic": 0,
            "reference_image_id": "0XYvRd7oD",
            "image": {
                "id": "0XYvRd7oD",
                "width": 1204,
                "height": 1445,
                "url": "https://cdn2.thecatapi.com/images/0XYvRd7oD.jpg",
            },
        },
        {
            "weight": {"imperial": "7 - 10", "metric": "3 - 5"},
            "id": "aege",
            "name": "Aegean",
            "vetstreet_url": "http://www.vetstreet.com/cats/aegean-cat",
            "temperament": "Affectionate, Social, Intelligent, Playful, Active",
            "origin": "Greece",
            "country_codes": "GR",
            "country_code": "GR",
            "description": "Native to the Greek islands known as the Cyclades in the Aegean Sea, these are natural cats, meaning they developed without humans getting involved in their breeding. As a breed, Aegean Cats are rare, although they are numerous on their home islands. They are generally friendly toward people and can be excellent cats for families with children.",
            "life_span": "9 - 12",
            "indoor": 0,
            "alt_names": "",
            "adaptability": 5,
            "affection_level": 4,
            "child_friendly": 4,
            "dog_friendly": 4,
            "energy_level": 3,
            "grooming": 3,
            "health_issues": 1,
            "intelligence": 3,
            "shedding_level": 3,
            "social_needs": 4,
            "stranger_friendly": 4,
            "vocalisation": 3,
            "experimental": 0,
            "hairless": 0,
            "natural": 0,
            "rare": 0,
            "rex": 0,
            "suppressed_tail": 0,
            "short_legs": 0,
            "wikipedia_url": "https://en.wikipedia.org/wiki/Aegean_cat",
            "hypoallergenic": 0,
            "reference_image_id": "ozEvzdVM-",
            "image": {
                "id": "ozEvzdVM-",
                "width": 1200,
                "height": 800,
                "url": "https://cdn2.thecatapi.com/images/ozEvzdVM-.jpg",
            },
        },
    ]


def mock_cat_detail():
    return {
        "weight": {"imperial": "6 - 12", "metric": "3 - 7"},
        "id": "beng",
        "name": "Bengal",
        "cfa_url": "http://cfa.org/Breeds/BreedsAB/Bengal.aspx",
        "vetstreet_url": "http://www.vetstreet.com/cats/bengal",
        "vcahospitals_url": "https://vcahospitals.com/know-your-pet/cat-breeds/bengal",
        "temperament": "Alert, Agile, Energetic, Demanding, Intelligent",
        "origin": "United States",
        "country_codes": "US",
        "country_code": "US",
        "description": "Bengals are a lot of fun to live with, but they're definitely not the cat for everyone, or for first-time cat owners. Extremely intelligent, curious and active, they demand a lot of interaction and woe betide the owner who doesn't provide it.",
        "life_span": "12 - 15",
        "indoor": 0,
        "lap": 0,
        "adaptability": 5,
        "affection_level": 5,
        "child_friendly": 4,
        "cat_friendly": 4,
        "dog_friendly": 5,
        "energy_level": 5,
        "grooming": 1,
        "health_issues": 3,
        "intelligence": 5,
        "shedding_level": 3,
        "social_needs": 5,
        "stranger_friendly": 3,
        "vocalisation": 5,
        "bidability": 3,
        "experimental": 0,
        "hairless": 0,
        "natural": 0,
        "rare": 0,
        "rex": 0,
        "suppressed_tail": 0,
        "short_legs": 0,
        "wikipedia_url": "https://en.wikipedia.org/wiki/Bengal_(cat)",
        "hypoallergenic": 1,
        "reference_image_id": "O3btzLlsO",
    }


def mock_image_search():
    return [
        {
            "id": "J2PmlIizw",
            "url": "https://cdn2.thecatapi.com/images/J2PmlIizw.jpg",
            "width": 1080,
            "height": 1350,
        },
        {
            "id": "8pCFG7gCV",
            "url": "https://cdn2.thecatapi.com/images/8pCFG7gCV.jpg",
            "width": 750,
            "height": 937,
        },
        {
            "id": "IFXsxmXLm",
            "url": "https://cdn2.thecatapi.com/images/IFXsxmXLm.jpg",
            "width": 973,
            "height": 973,
        },
        {
            "id": "VZ3qFLIe3",
            "url": "https://cdn2.thecatapi.com/images/VZ3qFLIe3.jpg",
            "width": 750,
            "height": 937,
        },
        {
            "id": "aaxNf4D0H",
            "url": "https://cdn2.thecatapi.com/images/aaxNf4D0H.jpg",
            "width": 1080,
            "height": 1350,
        },
    ]
