name: Test, Build & Deploy

on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [main]
  pull_request:
    branches: [main]
 
jobs:

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v2
      - run: pip install flake8
      - run: pip install -r requirements.txt
      - run: python -m manage test
      - run: flake8 api/ --max-line-length=127 # Runs flake 8 test to check code style

  build_publish_docker_image:
    runs-on: ubuntu-latest
    needs: [build_publish_docker_image]
    steps:
      - uses: actions/checkout@v3
      - name: Docker Login
        env:
          DOCKER_USER: ${{ secrets.DOCKER_USER }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
      - name: Build the Docker Image
        run: docker build . --file Dockerfile --tag ${{ secrets.DOCKER_USER }}/catwiki-django-be
      - name: Docker push
        if: github.ref == 'refs/heads/main' && github.event_name != 'pull_request'
        run: docker push ${{ secrets.DOCKER_USER }}/catwiki-django-be:latest
      

  pull_run_docker_image:
    if: github.ref == 'refs/heads/main' && github.event_name != 'pull_request'
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    needs: [build_publish_docker_image]
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Deploy Node Express TypeScript BE
        uses: appleboy/ssh-action@v0.1.2
        with:
          host: ${{secrets.SSH_HOST}} # IP address of the server you wish to ssh into
          key: ${{secrets.SSH_KEY}} # Private or Public key of the server
          username: ${{secrets.SSH_USERNAME}} # User of server you want to ssh into
          
          script: |
            docker pull ${{ secrets.DOCKER_USER }}/catwiki-django-be:latest
            docker stop catwiki-django-be
            docker rm catwiki-django-be
            docker run --name catwiki-django-be -it catwiki-django-be:latest -p 8020:8000